// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

package uk.me.uohiro.grpc.example.model;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calc.AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   */
  int getY();
}
