// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

package uk.me.uohiro.grpc.example.model;

public final class CalcProto {
  private CalcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calc_IntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calc_IntResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calc_AddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calc_AddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calc_SumRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calc_SumRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncalc.proto\022\004calc\"\034\n\013IntResponse\022\r\n\005val" +
      "ue\030\001 \001(\005\"\"\n\nAddRequest\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002" +
      " \001(\005\"\034\n\nSumRequest\022\016\n\006values\030\001 \003(\0052^\n\004Ca" +
      "lc\022*\n\003Add\022\020.calc.AddRequest\032\021.calc.IntRe" +
      "sponse\022*\n\003Sum\022\020.calc.SumRequest\032\021.calc.I" +
      "ntResponseB.\n\037uk.me.uohiro.grpc.example." +
      "modelB\tCalcProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_calc_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calc_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calc_IntResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_calc_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calc_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calc_AddRequest_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_calc_SumRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_calc_SumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calc_SumRequest_descriptor,
        new java.lang.String[] { "Values", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
