// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package uk.me.uohiro.grpc.example.model;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.routeguide.Point location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <code>.routeguide.Point location = 2;</code>
   */
  uk.me.uohiro.grpc.example.model.Point getLocation();
  /**
   * <code>.routeguide.Point location = 2;</code>
   */
  uk.me.uohiro.grpc.example.model.PointOrBuilder getLocationOrBuilder();
}
