// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package uk.me.uohiro.grpc.example.model;

public interface FeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.FeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  java.util.List<uk.me.uohiro.grpc.example.model.Feature> 
      getFeatureList();
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  uk.me.uohiro.grpc.example.model.Feature getFeature(int index);
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  java.util.List<? extends uk.me.uohiro.grpc.example.model.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  uk.me.uohiro.grpc.example.model.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
