// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

package uk.me.uohiro.grpc.example.model;

public interface IntResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calc.IntResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   */
  int getValue();
}
