// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

package uk.me.uohiro.grpc.example.model;

public interface SumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calc.SumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 values = 1;</code>
   */
  java.util.List<java.lang.Integer> getValuesList();
  /**
   * <code>repeated int32 values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated int32 values = 1;</code>
   */
  int getValues(int index);
}
